server:
  port: 8001

spring:
  application:
    name: cloud-test-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://172.31.231.195:3306/db_ccs?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: grouptwo
    password: grouptwo123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example # 实体所在的包名